USERNAME: "${ADA_USERNAME}"
PASSWORD: "${ADA_PASSWORD}"
HOMESERVER: $ADA_HOMESERVER|https://matrix.org
PREFIX: $ADA_PREFIX|!

env: development
log_level: DEBUG

bot:
  main_room: "!cHidtNcSgVLvluxHYZ:matrix.org"

extensions:
  welcome:
    room: "!cHidtNcSgVLvluxHYZ:matrix.org"