USERNAME: "${ADA_USERNAME}"
PASSWORD: "${ADA_PASSWORD}"
HOMESERVER: $ADA_HOMESERVER|https://matrix.org
PREFIX: "${ADA_PREFIX|!}"

env: development
log_level: DEBUG

bot:
  main_room: "${ADA_MAIN_ROOM|}"

extensions:
  welcome:
    room: "${ADA_MAIN_ROOM|}"
  weather:
    api_key: "${ADA_OPENWEATHER_API_KEY|}"
