USERNAME: "${ADA_USERNAME}"
PASSWORD: "${ADA_PASSWORD}"
HOMESERVER: $ADA_HOMESERVER|https://matrix.org
PREFIX: $ADA_PREFIX|!

env: production
log_level: INFO

bot:
  main_channel: "!OaOPoyVKqbmPEcMBbt:matrix.org"

extensions:
  welcome:
    channel: "!OaOPoyVKqbmPEcMBbt:matrix.org"