USERNAME: "${ADA_USERNAME}"
PASSWORD: "${ADA_PASSWORD}"
HOMESERVER: $ADA_HOMESERVER|https://matrix.org
PREFIX: "${ADA_PREFIX|!}"

env: production
log_level: INFO
database_url: DATABASE_URL

bot:
  main_room: "!OaOPoyVKqbmPEcMBbt:matrix.org"

extensions:
  welcome:
    room: "!OaOPoyVKqbmPEcMBbt:matrix.org"
